# Generated by Django 2.0.5 on 2018-05-25 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('UserName', models.CharField(default='', max_length=100)),
                ('ID_Aluno', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('ID_Artigo', models.AutoField(primary_key=True, serialize=False)),
                ('PDF_Artigo', models.CharField(default='', max_length=100)),
                ('Titulo', models.CharField(default='', max_length=300)),
                ('Resumo', models.CharField(default='', max_length=800)),
                ('Data_Publicao', models.DateField()),
                ('Autor', models.CharField(default='', max_length=100)),
                ('Area_Abordagem', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('DatasMarcadas', models.DateField()),
                ('Tema', models.CharField(default='', max_length=200)),
                ('ID_Reuniao', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Calendario_Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(default='', max_length=100)),
                ('ID_Reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.Calendario')),
            ],
        ),
        migrations.CreateModel(
            name='Computadores',
            fields=[
                ('ID_Maquina', models.AutoField(primary_key=True, serialize=False)),
                ('Status_Computador', models.BooleanField()),
                ('UserName', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('ID_Objeto', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(default='', max_length=100)),
                ('Descricao', models.CharField(default='', max_length=200)),
                ('Status_Objeto', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Maquina_Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.Computadores')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF_Pessoa', models.CharField(default='', max_length=11)),
                ('FotoPerfil', models.CharField(default='', max_length=50)),
                ('Data_Nascimento', models.DateField()),
                ('Lattes', models.CharField(default='', max_length=80)),
                ('Status', models.BooleanField()),
                ('UserName', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor_Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.Alunos')),
            ],
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('UserName', models.CharField(default='', max_length=100)),
                ('ID_Professor', models.AutoField(primary_key=True, serialize=False)),
                ('InteressePesquisa', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projetos_Pesquisas',
            fields=[
                ('ID_Pesquisa', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo_Pesquisa', models.CharField(default='', max_length=100)),
                ('Descricao_Pesquisa', models.CharField(default='', max_length=800)),
                ('Area_Pesquisa', models.CharField(default='', max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('ID_software', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(default='', max_length=100)),
                ('Descricao', models.CharField(default='', max_length=800)),
                ('Versao', models.CharField(default='', max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='professor_aluno',
            name='ID_Professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.Professores'),
        ),
        migrations.AddField(
            model_name='maquina_software',
            name='ID_Software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.Software'),
        ),
        migrations.AddField(
            model_name='alunos',
            name='ID_Maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.Computadores'),
        ),
    ]
