# Generated by Django 2.0.5 on 2018-06-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_remove_alunos_id_maquina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblioteca',
            name='PDF_Artigo',
        ),
    ]
