# Generated by Django 2.0.5 on 2018-06-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0003_remove_biblioteca_pdf_artigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='PDF_Arquivo',
            field=models.FileField(null=True, upload_to='arquivosBiblioteca/'),
        ),
    ]
