# Generated by Django 2.0.5 on 2018-06-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0005_auto_20180608_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblioteca',
            name='PDF_Arquivo',
        ),
    ]
