# Generated by Django 2.0.5 on 2018-06-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0010_remove_biblioteca_pdf_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='PDF_Arquivo',
            field=models.FileField(null=True, upload_to='pdf/'),
        ),
    ]
