# Generated by Django 2.0.5 on 2018-06-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0011_biblioteca_pdf_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='FotoPerfil',
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='PDF_Arquivo',
            field=models.FileField(null=True, upload_to='pdf'),
        ),
    ]
