# Generated by Django 2.0.5 on 2018-06-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0012_auto_20180608_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='FotoPerfil',
            field=models.FileField(null=True, upload_to='perfil'),
        ),
    ]
